"""
Apple Frangipan Tart — 14×8 gourmet kitchen for recipe 0.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 0 (Apple Frangipan Tart) — 6 components, 8 ingredient slots,
6 distinct tools (max cook 30t).
Category: Dessert.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("apple_frangipan_tart", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 0.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "bakeable", "count": 1},
    {"type": "dissolvable", "count": 1},
    {"type": "peelable", "count": 1},
    {"type": "poundable", "count": 1},
    {"type": "spreadable", "count": 1},
    {"type": "stirrable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 0
