"""
Banana Pancakes — 14×8 gourmet kitchen for recipe 14.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 14 (Banana Pancakes) — 6 components, 7 ingredient slots,
6 distinct tools (max cook 20t).
Category: Dessert.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("banana_pancakes", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 14.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "boilable", "count": 1},
    {"type": "cleanable", "count": 1},
    {"type": "peelable", "count": 1},
    {"type": "poundable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "stirrable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 14
