"""
BBQ Pork Sloppy Joes — 14×8 gourmet kitchen for recipe 30.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 30 (BBQ Pork Sloppy Joes) — 7 components, 13 ingredient slots,
7 distinct tools (max cook 10t).
Category: Pork.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("bbq_pork_sloppy_joes", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 30.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "cuttable", "count": 1},
    {"type": "dissolvable", "count": 1},
    {"type": "peelable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "scoopable", "count": 1},
    {"type": "shreddable", "count": 1},
    {"type": "squeezable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 30
