"""
Beef Banh Mi Bowls with Sriracha Mayo, Carrot & Pickled Cucumber — 14×8 gourmet kitchen for recipe 31.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 31 (Beef Banh Mi Bowls with Sriracha Mayo, Carrot & Pickled Cucumber) — 5 components, 8 ingredient slots,
5 distinct tools (max cook 20t).
Category: Beef.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("beef_banh_mi_bowls_with_sriracha_mayo_carrot_pickled_cucumber", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 31.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "boilable", "count": 1},
    {"type": "cuttable", "count": 1},
    {"type": "peelable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "stirrable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 31
