"""
Broccoli & Stilton soup — 14×8 gourmet kitchen for recipe 12.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 12 (Broccoli & Stilton soup) — 6 components, 9 ingredient slots,
6 distinct tools (max cook 8t).
Category: Starter.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("broccoli_stilton_soup", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 12.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "cleanable", "count": 1},
    {"type": "cuttable", "count": 1},
    {"type": "peelable", "count": 1},
    {"type": "poundable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "spreadable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 12
