"""
Chicken Enchilada Casserole — 14×8 gourmet kitchen for recipe 44.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 44 (Chicken Enchilada Casserole) — 4 components, 4 ingredient slots,
4 distinct tools (max cook 10t).
Category: Chicken.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("chicken_enchilada_casserole", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 44.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "cuttable", "count": 1},
    {"type": "kneadable", "count": 1},
    {"type": "meltable", "count": 1},
    {"type": "pourable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 44
