"""
Egyptian Fatteh — 14×8 gourmet kitchen for recipe 101.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 101 (Egyptian Fatteh) — 8 components, 15 ingredient slots,
8 distinct tools (max cook 30t).
Category: Beef.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("egyptian_fatteh", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 101.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "bakeable", "count": 1},
    {"type": "boilable", "count": 1},
    {"type": "cuttable", "count": 1},
    {"type": "dissolvable", "count": 1},
    {"type": "peelable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "shreddable", "count": 1},
    {"type": "spreadable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 101
