"""
Eton Mess — 14×8 gourmet kitchen for recipe 96.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 96 (Eton Mess) — 5 components, 5 ingredient slots,
5 distinct tools (max cook 8t).
Category: Dessert.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("eton_mess", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 96.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "cleanable", "count": 1},
    {"type": "cuttable", "count": 1},
    {"type": "poundable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "stirrable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 96
