"""
Fruit and Cream Cheese Breakfast Pastries — 14×8 gourmet kitchen for recipe 112.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 112 (Fruit and Cream Cheese Breakfast Pastries) — 6 components, 8 ingredient slots,
6 distinct tools (max cook 10t).
Category: Breakfast.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("fruit_and_cream_cheese_breakfast_pastries", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 112.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "cleanable", "count": 1},
    {"type": "dissolvable", "count": 1},
    {"type": "kneadable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "siftable", "count": 1},
    {"type": "spreadable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 112
