"""
Honey Teriyaki Salmon — 14×8 gourmet kitchen for recipe 127.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 127 (Honey Teriyaki Salmon) — 3 components, 5 ingredient slots,
3 distinct tools (max cook 8t).
Category: Seafood.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("honey_teriyaki_salmon", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 127.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "cuttable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "toastable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 127
