"""
Kentucky Fried Chicken — 14×8 gourmet kitchen for recipe 141.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 141 (Kentucky Fried Chicken) — 8 components, 17 ingredient slots,
8 distinct tools (max cook 20t).
Category: Chicken.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("kentucky_fried_chicken", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 141.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "cuttable", "count": 1},
    {"type": "dryable", "count": 1},
    {"type": "poundable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "shreddable", "count": 1},
    {"type": "siftable", "count": 1},
    {"type": "stirrable", "count": 1},
    {"type": "topable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 141
