"""
Mbuzi Choma (Roasted Goat) — 14×8 gourmet kitchen for recipe 175.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 175 (Mbuzi Choma (Roasted Goat)) — 3 components, 7 ingredient slots,
3 distinct tools (max cook 5t).
Category: Goat.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("mbuzi_choma_roasted_goat", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 175.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "cuttable", "count": 1},
    {"type": "shreddable", "count": 1},
    {"type": "stirrable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 175
