"""
Portuguese custard tarts — 14×8 gourmet kitchen for recipe 213.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 213 (Portuguese custard tarts) — 7 components, 11 ingredient slots,
7 distinct tools (max cook 20t).
Category: Dessert.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("portuguese_custard_tarts", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 213.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "blendable", "count": 1},
    {"type": "boilable", "count": 1},
    {"type": "dissolvable", "count": 1},
    {"type": "kneadable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "shreddable", "count": 1},
    {"type": "stirrable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 213
