"""
Ribollita — 14×8 gourmet kitchen for recipe 218.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 218 (Ribollita) — 7 components, 14 ingredient slots,
7 distinct tools (max cook 20t).
Category: Vegetarian.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("ribollita", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 218.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "boilable", "count": 1},
    {"type": "cleanable", "count": 1},
    {"type": "cuttable", "count": 1},
    {"type": "peelable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "shreddable", "count": 1},
    {"type": "soakable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 218
