"""
Rocky Road Fudge — 14×8 gourmet kitchen for recipe 216.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 216 (Rocky Road Fudge) — 4 components, 5 ingredient slots,
4 distinct tools (max cook 30t).
Category: Dessert.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("rocky_road_fudge", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 216.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "bakeable", "count": 1},
    {"type": "meltable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "spreadable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 216
