"""
Rogaliki (Polish Croissant Cookies) — 14×8 gourmet kitchen for recipe 226.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 226 (Rogaliki (Polish Croissant Cookies)) — 3 components, 6 ingredient slots,
3 distinct tools (max cook 5t).
Category: Dessert.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("rogaliki_polish_croissant_cookies", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 226.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "siftable", "count": 1},
    {"type": "spreadable", "count": 1},
    {"type": "stirrable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 226
