"""
Rosół (Polish Chicken Soup) — 14×8 gourmet kitchen for recipe 225.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 225 (Rosół (Polish Chicken Soup)) — 6 components, 13 ingredient slots,
6 distinct tools (max cook 30t).
Category: Chicken.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("ros_polish_chicken_soup", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 225.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "bakeable", "count": 1},
    {"type": "boilable", "count": 1},
    {"type": "cleanable", "count": 1},
    {"type": "cuttable", "count": 1},
    {"type": "peelable", "count": 1},
    {"type": "shreddable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 225
