"""
Smoked Haddock Kedgeree — 14×8 gourmet kitchen for recipe 255.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 255 (Smoked Haddock Kedgeree) — 6 components, 12 ingredient slots,
6 distinct tools (max cook 20t).
Category: Breakfast.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("smoked_haddock_kedgeree", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 255.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "boilable", "count": 1},
    {"type": "cleanable", "count": 1},
    {"type": "cuttable", "count": 1},
    {"type": "peelable", "count": 1},
    {"type": "shreddable", "count": 1},
    {"type": "spreadable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 255
