"""
Soy-Glazed Meatloaves with Wasabi Mashed Potatoes & Roasted Carrots — 14×8 gourmet kitchen for recipe 259.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 259 (Soy-Glazed Meatloaves with Wasabi Mashed Potatoes & Roasted Carrots) — 7 components, 11 ingredient slots,
7 distinct tools (max cook 10t).
Category: Beef.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("soy_glazed_meatloaves_with_wasabi_mashed_potatoes_roasted_carrots", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 259.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "cuttable", "count": 1},
    {"type": "dissolvable", "count": 1},
    {"type": "peelable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "spreadable", "count": 1},
    {"type": "stirrable", "count": 1},
    {"type": "topable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 259
