"""
Spring onion and prawn empanadas — 14×8 gourmet kitchen for recipe 265.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 265 (Spring onion and prawn empanadas) — 7 components, 10 ingredient slots,
7 distinct tools (max cook 20t).
Category: Seafood.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("spring_onion_and_prawn_empanadas", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 265.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "boilable", "count": 1},
    {"type": "cuttable", "count": 1},
    {"type": "peelable", "count": 1},
    {"type": "poundable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "spreadable", "count": 1},
    {"type": "stirrable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 265
