"""
Sticky Toffee Pudding Ultimate — 14×8 gourmet kitchen for recipe 231.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 231 (Sticky Toffee Pudding Ultimate) — 7 components, 13 ingredient slots,
7 distinct tools (max cook 20t).
Category: Dessert.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("sticky_toffee_pudding_ultimate", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 231.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "boilable", "count": 1},
    {"type": "dissolvable", "count": 1},
    {"type": "peelable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "scoopable", "count": 1},
    {"type": "spreadable", "count": 1},
    {"type": "stirrable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 231
