"""
Stovetop Eggplant With Harissa, Chickpeas, and Cumin Yogurt — 14×8 gourmet kitchen for recipe 233.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 233 (Stovetop Eggplant With Harissa, Chickpeas, and Cumin Yogurt) — 8 components, 8 ingredient slots,
8 distinct tools (max cook 20t).
Category: Vegetarian.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("stovetop_eggplant_with_harissa_chickpeas_and_cumin_yogurt", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 233.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "blendable", "count": 1},
    {"type": "cleanable", "count": 1},
    {"type": "cuttable", "count": 1},
    {"type": "peelable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "soakable", "count": 1},
    {"type": "stirrable", "count": 1},
    {"type": "topable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 233
