"""
Turkey Meatloaf — 14×8 gourmet kitchen for recipe 274.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 274 (Turkey Meatloaf) — 8 components, 11 ingredient slots,
8 distinct tools (max cook 20t).
Category: Miscellaneous.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("turkey_meatloaf", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 274.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "boilable", "count": 1},
    {"type": "cuttable", "count": 1},
    {"type": "formable", "count": 1},
    {"type": "peelable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "scoopable", "count": 1},
    {"type": "stirrable", "count": 1},
    {"type": "toastable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 274
