"""
Vegan Chocolate Cake — 14×8 gourmet kitchen for recipe 291.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 291 (Vegan Chocolate Cake) — 6 components, 8 ingredient slots,
6 distinct tools (max cook 30t).
Category: Vegan.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("vegan_chocolate_cake", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 291.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "bakeable", "count": 1},
    {"type": "blendable", "count": 1},
    {"type": "boilable", "count": 1},
    {"type": "dissolvable", "count": 1},
    {"type": "pourable", "count": 1},
    {"type": "stirrable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 291
