"""
White chocolate creme brulee — 14×8 gourmet kitchen for recipe 297.

Auto-generated by scripts/generate_recipe_layouts.py — same kumpir GRID
(large open floor, central counter island), items seed-placed by the
layout_builder.

Recipe 297 (White chocolate creme brulee) — 4 components, 5 ingredient slots,
4 distinct tools (max cook 10t).
Category: Dessert.

Usage:
    from custom_layouts.layout_builder import load
    layout = load("white_chocolate_creme_brulee", seed=0)
"""

GRID = """
WWWWWWWWWWWWWW
W            W
W  WWWWWWWW  W
W  W      W  W
W  W      W  W
W  WWWWWWWW  W
W            W
WWWWWWWWWWWWWW
""".strip()

ITEMS = [
    # One auto-placed dispenser per unique ingredient in recipe 297.
    {"type": "dispenser", "from_recipe": True},
    # One tool per recipe component (deduplicated by tool_type).
    {"type": "blendable", "count": 1},
    {"type": "dissolvable", "count": 1},
    {"type": "meltable", "count": 1},
    {"type": "stirrable", "count": 1},
    # Plating & delivery
    {"type": "plate_pile", "count": 1},
    {"type": "goal",       "count": 1},
]

RECIPES = 297
